### PR TITLE
feat: Fixed file structure

### PR DESCRIPTION
**Pull request by lakshyabatman**
Hello,
I added files into their respective folders, so this way the codebase looks much more cleaner, and then these files can be divided sub-modules and placed in the same folder in future.

**POINT TO NOTE**
On running example, I came across an issue 
```
import 'sphere/dist/index.css' // This file doesn't exist.
```
I've commented out the import for now.

### CODE REVIEW

**Comment by lakshyabatman** [comment]
@Souvikns , can you have a look on this PR please

**Comment by Souvikns** [comment]
I guess this fixes #10

**Comment by lakshyabatman** [comment]
Yes, please have a look on it.

**Comment by Souvikns** [comment]
Yeah, it is fine. I am merging this pr.

**Pull request merged**
